### ISSUE TITLE
endless loading spinner

### ISSUE THREAD

**Issue by sotomaque** [wesharehoodies/react-native-redux-crypto-tracker#2]
Hello i followed your tutorial and was able to get it all to work, except for the final part. after after changing CryptoContainer.js i am stuck with an endless Loading spinner.  any idea whats causing this?  
![simulator screen shot - iphone x - 2017-11-21 at 00 30 16](https://user-images.githubusercontent.com/7506954/33058030-373c1b02-ce53-11e7-9454-234db298da8b.png)
<img width="821" alt="screen shot 2017-11-21 at 12 30 24 am" src="https://user-images.githubusercontent.com/7506954/33058031-374d39a0-ce53-11e7-8475-43aa571cf594.png">

**Comment by jzoric** [comment]
Look at the `CryptoReducer.js` source code for `chapter4`. In tutorial it's
`Object.assign(state, {...}}` but it should be written as `Object.assign({}, state, {...}}`

I believe this should fix your endless loop problem.
