### ISSUE TITLE
[Chapter 2] - Tutorial code wont run, Downloaded code produces a blank screen in iOS simulator

### ISSUE THREAD

**Issue by Pushplaybang** [wesharehoodies/react-native-redux-crypto-tracker#3]
Hi There 

Downloaded the coded after trying to find a bug in my own code that kept throwing an error, to compare.  On caparison I couldn't spot a difference, so I ran your code and get a blank white screen with no error message at all.

any thoughts on where to start? deps? system?

**Comment by Pushplaybang** [comment]
downloading and running the chapter 4 version works flawlessly

**Comment by wesharehoodies** [comment]
Which error? Try restarting the simulator.

**Comment by Pushplaybang** [comment]
in my code 
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
```

in the downloaded code, no error, just continuous loading spinner.

**Comment by Pushplaybang** [comment]
Ok after multiple restarts, its now working..... closing as a random simulator error maybe?
